apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: kube-logging
data:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: true
    