apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autograder-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: autograder
  namespace: default
roleRef:
  kind: Role
  name: autograder-role
  apiGroup: rbac.authorization.k8s.io