apiVersion: batch/v1
kind: Job
metadata:
  name: file-execution-job
spec:
  ttlSecondsAfterFinished: 600  # Delete the Job and its Pods 600 seconds (10 minutes) after it completes
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: testrunner-container
        image: testrunner:latest
        imagePullPolicy: IfNotPresent
        args: ["/input/hello_world/hello_world.py", "hello_world"]  # Argument to the container. You must provide exactly 2 arguments: <input_file>, <problem_id>
        volumeMounts:
        - name: file-volume
          mountPath: /input
      restartPolicy: Never
      volumes:
      - name: file-volume
        persistentVolumeClaim:
          claimName: autograder-pvc